// Powered by OnSpace.AI
export const config = {
  appName: 'My Easy Life Guru',
  guruName: 'Guru Kai',
  readingLevel: 5,
  
  // Feature flags
  features: {
    accountCreationOptional: true,
    documentDownload: true,
    documentHighlighting: true,
    mealPlanning: true,
    webSearch: true,
    emailDrafting: true,
    textDrafting: true,
    mapIntegration: true,
    reminderNotifications: true,
    chatSaveProgress: true,
    guruCustomization: true,
  },
  
  // Guru Kai animations
  guruAnimations: {
    flyInDuration: 600,
    flyOutDuration: 400,
    growDuration: 300,
    floatDuration: 3000,
  },
  
  // Chat settings
  chat: {
    maxMessageLength: 500,
    autoSaveInterval: 5000, // 5 seconds
    typingSpeed: 30, // ms per character
  },
  
  // UI settings
  ui: {
    showAds: true,
    adHeight: 50, // Small banner
    comprehensionCheckButtons: ['Yes', 'No', 'Explain Better'],
    guruPositions: {
      topRight: { top: 60, right: 16 },
      centered: { alignItems: 'center', justifyContent: 'center' },
    },
  },
  
  // Default example prompts
  examplePrompts: [
    'Help me apply for EBT',
    'Build me a $50 meal plan',
    'Show me how to file taxes',
    'Help me write a resume',
    'Type "Menu" to see all I can help with',
  ],
};

export const toolCategories = [
  {
    id: 'money-id',
    name: 'Money & ID',
    icon: 'account-balance-wallet',
    color: '#EC4899',
    tools: [
      { id: 'id-checklist', name: 'The ID Checklist', difficulty: 'Easy' },
      { id: 'open-bank', name: 'Money Basics: Open Bank Account', difficulty: 'Easy' },
      { id: 'credit-score', name: 'Better Credit: Free Credit Score', difficulty: 'Easy' },
      { id: 'simple-budget', name: 'The Simple Budget (50/30/20)', difficulty: 'Easy' },
      { id: 'credit-cards', name: 'Credit Cards: Good vs Trap', difficulty: 'Medium' },
      { id: 'emergency-fund', name: 'Emergency Fund: Save First $100', difficulty: 'Easy' },
      { id: 'social-security-card', name: 'Replace Social Security Card', difficulty: 'Easy' },
      { id: 'file-taxes', name: 'Taxes Made Easy: File Free', difficulty: 'Medium' },
      { id: 'protect-ssn', name: 'Protecting Your SSN', difficulty: 'Easy' },
      { id: 'think-about-it', name: 'Never Sign Same Day', difficulty: 'Easy' },
    ],
  },
  {
    id: 'housing-utilities',
    name: 'Housing & Utilities',
    icon: 'home',
    color: '#8B5CF6',
    tools: [
      { id: 'cheap-housing', name: 'Find Low Income Housing', difficulty: 'Medium' },
      { id: 'rent-ready', name: 'Rent Ready: Required Papers', difficulty: 'Easy' },
      { id: 'utility-discount', name: 'Discount on Bills', difficulty: 'Easy' },
      { id: 'security-deposit', name: 'Get Security Deposit Back', difficulty: 'Medium' },
      { id: 'find-room', name: 'Find Cheap Room Safely', difficulty: 'Medium' },
      { id: 'tenant-rights', name: 'Know Your Tenant Rights', difficulty: 'Easy' },
      { id: 'po-box', name: 'Get a PO Box', difficulty: 'Easy' },
      { id: 'laundromat', name: 'Laundry 101', difficulty: 'Easy' },
      { id: 'utilities-setup', name: 'Start Your Own Utilities', difficulty: 'Easy' },
      { id: 'first-apartment', name: 'First Apartment Kit', difficulty: 'Easy' },
    ],
  },
  {
    id: 'work-school',
    name: 'Work & School',
    icon: 'work',
    color: '#10B981',
    tools: [
      { id: 'job-search', name: 'Find Jobs Hiring Now', difficulty: 'Easy' },
      { id: 'interview-prep', name: 'The Interview: What to Say', difficulty: 'Easy' },
      { id: 'resume', name: 'Write Your Resume', difficulty: 'Easy' },
      { id: 'professional-email', name: 'Create Professional Email', difficulty: 'Easy' },
      { id: 'professional-voice', name: 'Talk to Boss Professionally', difficulty: 'Easy' },
      { id: 'remote-work', name: 'Find Remote Jobs', difficulty: 'Medium' },
      { id: 'mental-health-days', name: 'Ask for Day Off', difficulty: 'Easy' },
      { id: 'professional-dress', name: 'Thrift Store Professional Look', difficulty: 'Easy' },
      { id: 'ged', name: 'Get Your GED', difficulty: 'Medium' },
      { id: 'fafsa', name: 'FAFSA & Grants Over 25', difficulty: 'Hard' },
    ],
  },
  {
    id: 'food-health',
    name: 'Food & Health',
    icon: 'restaurant',
    color: '#06B6D4',
    tools: [
      { id: 'ebt', name: 'Apply for EBT/Food Stamps', difficulty: 'Easy' },
      { id: 'grocery-list', name: 'Cheap Grocery List', difficulty: 'Easy' },
      { id: 'doctor-visit', name: 'Make Doctor Appointment', difficulty: 'Easy' },
      { id: 'eye-dental', name: 'Free Eye & Dental Checkups', difficulty: 'Easy' },
      { id: 'health-insurance', name: 'Get Medicaid', difficulty: 'Easy' },
      { id: 'first-aid', name: 'Home First Aid Kit', difficulty: 'Easy' },
      { id: 'wic', name: 'WIC for Baby & Moms', difficulty: 'Easy' },
      { id: 'free-clinics', name: 'Find Sliding Scale Clinics', difficulty: 'Easy' },
      { id: 'meal-prep', name: 'Cook Once, Eat 3 Days', difficulty: 'Easy' },
      { id: 'mental-health', name: 'Find Free Therapist', difficulty: 'Easy' },
    ],
  },
  {
    id: 'legal-systems',
    name: 'Legal & Systems',
    icon: 'gavel',
    color: '#EF4444',
    tools: [
      { id: 'court-basics', name: 'Court Basics: What to Wear', difficulty: 'Medium' },
      { id: 'public-records', name: 'Check Your Record', difficulty: 'Easy' },
      { id: 'jury-duty', name: 'Handle Jury Duty Letter', difficulty: 'Easy' },
      { id: 'housing-office', name: 'Talk to Housing Authority', difficulty: 'Medium' },
      { id: 'disability', name: 'Apply for Disability', difficulty: 'Hard' },
      { id: 'legal-aid', name: 'Find Free Lawyer', difficulty: 'Easy' },
      { id: 'child-support', name: 'Child Support System', difficulty: 'Medium' },
      { id: 'unemployment', name: 'File Unemployment', difficulty: 'Easy' },
      { id: 'dispute-bills', name: 'Dispute Bills or Decisions', difficulty: 'Medium' },
      { id: 'notary', name: 'What is a Notary?', difficulty: 'Easy' },
    ],
  },
  {
    id: 'transportation-tech',
    name: 'Transportation & Tech',
    icon: 'directions-car',
    color: '#F59E0B',
    tools: [
      { id: 'car-buy', name: 'Check Used Car Before Buying', difficulty: 'Medium' },
      { id: 'flat-tire', name: 'Change a Flat Tire', difficulty: 'Easy' },
      { id: 'car-insurance', name: 'Get Cheap Car Insurance', difficulty: 'Easy' },
      { id: 'check-engine', name: 'Read Check Engine Light', difficulty: 'Easy' },
      { id: 'public-transit', name: 'Use Bus/Dial-a-Ride', difficulty: 'Easy' },
      { id: 'password-security', name: 'Create Safe Passwords', difficulty: 'Easy' },
      { id: 'job-scam', name: 'Spot Fake Job Scams', difficulty: 'Easy' },
      { id: 'free-phone', name: 'Get Free Government Phone', difficulty: 'Easy' },
      { id: 'safe-selling', name: 'Sell Online Safely', difficulty: 'Easy' },
      { id: 'social-cleanup', name: 'Clean Up Social Media', difficulty: 'Easy' },
    ],
  },
  {
    id: 'emergency-survival',
    name: 'Emergency Survival',
    icon: 'warning',
    color: '#EF4444',
    tools: [
      { id: 'go-bag', name: 'Pack a 3-Day Go Bag', difficulty: 'Easy' },
      { id: 'blackout', name: 'Power Outage Survival', difficulty: 'Easy' },
      { id: 'water-shutoff', name: 'Find Water Valve', difficulty: 'Easy' },
      { id: 'ice-contact', name: 'Set ICE Contact', difficulty: 'Easy' },
      { id: 'emergency-cooking', name: 'Cook Without Power', difficulty: 'Easy' },
      { id: 'evacuation', name: 'Know Evacuation Routes', difficulty: 'Easy' },
      { id: 'first-aid-hacks', name: 'First Aid Without Supplies', difficulty: 'Easy' },
      { id: 'paper-backup', name: 'Keep Paper Phone Numbers', difficulty: 'Easy' },
      { id: 'extreme-temp', name: 'Survive Heat/Cold', difficulty: 'Easy' },
      { id: 'emergency-cash', name: 'Hide $20 Emergency Cash', difficulty: 'Easy' },
    ],
  },
  {
    id: 'healing-support',
    name: 'Healing & Support',
    icon: 'favorite',
    color: '#EC4899',
    tools: [
      { id: 'sliding-scale', name: 'Find Affordable Therapy', difficulty: 'Easy' },
      { id: 'rehab-no-insurance', name: 'Find Free Rehab', difficulty: 'Medium' },
      { id: 'online-therapy', name: 'Online Therapy with Aid', difficulty: 'Easy' },
      { id: 'find-help-tool', name: 'Use FindSupport.gov', difficulty: 'Easy' },
      { id: 'support-groups', name: 'Find AA/NA Meetings', difficulty: 'Easy' },
      { id: 'online-meetings', name: 'Join Online Support Groups', difficulty: 'Easy' },
      { id: 'crisis-text', name: 'Crisis Text Line (741741)', difficulty: 'Easy' },
      { id: 'warm-lines', name: 'Call Warm Line to Vent', difficulty: 'Easy' },
      { id: 'medicaid-rehab', name: 'Use Medicaid for Rehab', difficulty: 'Medium' },
      { id: 'community-mentors', name: 'Find a Sponsor', difficulty: 'Easy' },
    ],
  },
  {
    id: 'quick-cash',
    name: 'Quick Cash & Level-Up',
    icon: 'attach-money',
    color: '#10B981',
    tools: [
      { id: 'donate-plasma', name: 'Donate Plasma for $500+', difficulty: 'Easy' },
      { id: 'marketplace-flip', name: 'Flip Free Items for Cash', difficulty: 'Easy' },
      { id: 'gig-apps', name: 'Gig Jobs Without Car', difficulty: 'Easy' },
      { id: 'delivery-foot', name: 'Deliver on Foot/Bike', difficulty: 'Easy' },
      { id: 'what-to-sell', name: 'What Sells Fast', difficulty: 'Easy' },
      { id: 'free-certs', name: 'Get Free Skill Certificates', difficulty: 'Easy' },
      { id: 'buy-nothing', name: 'Join Buy Nothing Groups', difficulty: 'Easy' },
      { id: 'library-perks', name: 'Free Library Resources', difficulty: 'Easy' },
      { id: 'budget-travel', name: 'Travel Cheap', difficulty: 'Easy' },
      { id: 'day-labor', name: 'Find Day Labor Jobs', difficulty: 'Easy' },
    ],
  },
  {
    id: 'parenting-family',
    name: 'Parenting & Family',
    icon: 'child-care',
    color: '#A78BFA',
    tools: [
      { id: 'free-baby-gear', name: 'Free Baby Gear & Diapers', difficulty: 'Easy' },
      { id: 'wic-benefits', name: 'Maximize WIC Benefits', difficulty: 'Easy' },
      { id: 'childcare-subsidy', name: 'Get Help Paying Childcare', difficulty: 'Medium' },
      { id: 'sick-kid-plan', name: 'Sick Kid Backup Plan', difficulty: 'Easy' },
      { id: 'cheap-family-fun', name: 'Museums for All ($3 Entry)', difficulty: 'Easy' },
      { id: 'thrift-parenting', name: 'Never Buy Baby Clothes New', difficulty: 'Easy' },
      { id: 'library-storytime', name: 'Free Library Story Time', difficulty: 'Easy' },
      { id: 'head-start', name: 'Apply for Head Start', difficulty: 'Medium' },
      { id: 'baby-proof', name: 'Baby-Proof on Budget', difficulty: 'Easy' },
      { id: 'future-savings', name: 'Start 529 or Kid Savings', difficulty: 'Medium' },
    ],
  },
];
